language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: tWWjQvWu4GqZwqIeNfhiMHoawdp5mncHcC5wDMMR5SsybDyt1lROWaAludJcNVU1lwyR/xnc/LAUa8QTRy4gXN9CAErfvB0QTiKKJA10kVMZRaZOLprdA6vG4VVczoWt6bMNd+W6Et0vdE24U4gA1YgD9xGIDE5IEzEBZEXRItDuXWeKagEFF+LM6sebaTHx9K+r3sG2zQEuEl+OElskrmr/q+Gmzks0gyMqGbecl6xUg12DwfxreFFAng6P8VydqmD8trvboRvokjNHpOv4hc4fnC2uKxTyztb+G04hiLCfrixmAakiHqap1RIJzzyYq2zaBxjs7HWIeaiPkYoye2oN7IGxDonwvKYMww54h/4L9Xb/kyGTqK6lNPo+YcleG5ygQRxw08eSsd4YNDHbfw7mJ8uLCf/N7k3Rv961plerfdjZ85L4uiHqq/tMat8nuVV9BDzoXhxXg/9iSIFFLh7JDOTfXMcWVJCYvwqki7YTEsLEUR4tNXJhUv5W/ytHIhT40qWFSfKUed4IN1VSDH3R2ardVKHmrXnzL8309P4EF5u07/NwDy1zoJ5soILVJaCd3uBv2nfxHfnBEv+it1A0fZH1f8qZHl6bIafVuKdgTgHruWOt7jUuRiMMbU5IRJXdLuGudnEAXvrqJeuTzB0RVG0tQACyiTuOClSoY2I=
  app: shopping
  on:
    repo: ragnar-pwninskjold/shopping
